services:
  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    restart: unless-stopped
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./rule.yml:/etc/prometheus/rule.yml
        #links:
        #- alertmanager:alertmanager
  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    command:
      - '--path.rootfs=/host'
    network_mode: host
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'
  alertmanager:
    image: prom/alertmanager
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager/config.yml:/etc/alertmanager/config.yml
    restart: on-failure
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
  prometheus-bot:
    image: aminvakil/prometheus_bot
    volumes:
      - "./tgbot/config.yaml:/config.yaml"
    ports:
      - 9087:9087
        #command:
        #  - "/prometheus_bot -c /etc/tgbot/config.yaml -l 9087"
    restart: always
