rule_files:
  - rule.yml
scrape_configs:
- job_name: node
  scrape_interval: 5s
  static_configs:
  - targets:
    - 3.66.189.34:9100
    - 18.195.117.15:9100
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 3.66.189.34:9093
