rule_files:
  - rule.yml
scrape_configs:
- job_name: node
  scrape_interval: 5s
  static_configs:
  - targets:
    - first_host_ip:9100
    - second_host_ip:9100
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager_ip:9093
