groups:
  - name: CPU_Usage_Alerts
    rules:
      - alert: HighCPUUsage
        #expr: 100 * (1 - avg by(instance) (rate(node_cpu_seconds_total{mode="user"}[1m]))) > 80
        expr: 100 - (avg(irate(node_cpu_seconds_total{mode="idle"}[1m])) * 100) > 80
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "High CPU usage detected on {{ $labels.instance }}"
          description: "CPU usage on instance {{ $labels.instance }} has been above 80% for the last 5 minutes."
